
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 53
#define YY_END_OF_BUFFER 54
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[414] =
    {   0,
        0,    0,   54,   52,   51,    1,   52,   52,   48,    9,
       49,   49,   49,   49,   49,   49,   49,   49,   31,   49,
       49,   49,   49,   49,   49,    9,   49,   49,   49,   49,
       49,   49,   49,   49,   31,   49,   49,   49,   49,   49,
       49,   30,   51,    0,   48,   47,   49,   49,   49,   49,
       49,   49,   14,   49,   49,   15,   20,   49,   49,   49,
       49,   16,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,    0,   49,   49,   49,   49,   49,   49,
       14,   49,   49,   15,   20,   49,   49,   49,   49,   16,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,

       49,   46,   47,   49,   49,   49,   49,   18,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   13,   49,   49,
       49,   49,   36,   17,   49,   49,   49,   49,   41,   49,
       49,   50,   49,   49,   49,   49,   18,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   13,   49,   49,   49,
       49,   36,   17,   49,   49,   49,   49,   41,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   49,    0,   49,
       49,   49,   40,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,

       49,   49,   49,   49,   49,   40,   49,   49,   49,   49,
       49,   34,   49,   49,   49,   23,   49,   49,   49,   28,
       49,   49,   49,   49,   49,    0,   49,   32,   12,   26,
       49,   49,   49,   49,   34,   49,   49,   49,   23,   49,
       49,   49,   28,   49,   49,   49,   49,   49,   49,   32,
       12,   26,   49,   49,   49,   49,   33,   49,   49,   49,
       49,   49,   49,   49,   49,    0,   49,   45,    0,   49,
       49,   49,   49,   49,   33,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   45,   49,   49,   49,   49,   25,
       49,   49,   49,   49,   49,   49,   49,   49,    0,   35,

        0,   49,    0,   49,   49,   49,   49,   25,   49,   49,
       49,   49,   49,   49,   49,   49,   35,   49,   49,   49,
        0,   49,   49,   49,    6,   22,   49,   38,   19,   49,
        0,    0,    0,    0,   49,   49,   49,   49,   49,    6,
       22,   49,   38,   19,   49,   49,   49,    0,   49,   49,
       29,   49,   37,    0,    0,    0,   27,   49,   49,   49,
       49,   29,   49,   37,   49,   21,    0,    2,   49,    7,
       24,    0,   44,    0,   10,   11,   21,    2,   49,    7,
       24,   10,   11,   42,   49,    5,    0,   43,    8,   49,
        5,    8,   49,   49,    0,   49,   49,   49,   49,   39,

       49,   49,   49,   49,   49,   49,    3,   49,    3,   49,
        4,    4,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    5,    6,    1,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    1,    1,    1,
        1,    1,    1,    1,    8,    9,   10,   11,   12,   13,
        9,    9,   14,    9,    9,   15,   16,    9,   17,   18,
       19,    9,   20,   21,   22,   23,    9,    9,    9,    9,
        1,    1,    1,    1,   24,    1,   25,   26,   27,   28,

       29,   30,   31,   32,   33,   32,   32,   34,   35,   36,
       37,   38,   39,   40,   41,   42,   43,   44,   32,   32,
       45,   46,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[47] =
    {   0,
        1,    1,    1,    2,    1,    1,    1,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    1,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4
    } ;

static const flex_int16_t yy_base[417] =
    {   0,
        0,    0, 1004, 1005, 1001, 1005,    0,  995,   41,   22,
        0,   25,   22,   20,  972,   21,   33,   35,  960,  962,
      955,  968,   39,  960,  970,   71,   91,   94,   97,  106,
      112,  118,  119,  130,  135,  137,  136,  153,  156,  159,
      171,  158,  992,  989,   59,  985,    0,  949,  950,  962,
      953,  951,  945,  128,  949,  951,    0,  941,  947,  938,
      939,    0,  934,   26,  943,  943,  929,  939,   43,  941,
      938,   40,  931,    0,  174,  176,  179,  182,  194,  195,
      197,  203,  210,  212,  221,  223,  228,  229,  230,  246,
      247,  248,  253,  264,  259,  275,  276,  282,  284,  291,

      299, 1005,  957,  912,  910,  909,  110,    0,  900,  895,
      873,  885,  874,  871,  859,  854,  848,    0,  848,  835,
      824,  835,    0,    0,  851,  822,  811,  803,    0,  797,
      795,    0,  300,  307,  308,  320,  325,  326,  333,  328,
      344,  346,  351,  357,  364,  370,  352,  363,  369,  376,
      385,  382,  388,  400,  391,  394,  403,  406,  411,  412,
      799,  783,  773,  775,  767,  770,  753,  757,  756,  741,
      747,  725,  719,  709,  690,  690,  681,  673,  673,  668,
      666,  647,    0,  641,  423,  428,  429,  430,  431,  446,
      449,  451,  452,  464,  472,  473,  481,  479,  480,  497,

      498,  500,  503,  518,  515,  520,  523,  633,  640,  634,
      627,  606,  609,  615,  594,    0,  593,  594,  594,    0,
      580,  586,  616,  566,  575,  564,  559,    0,    0,    0,
      521,  540,  541,  548,  539,  547,  563,  560,  566,  572,
      571,  583,  584,  590,  592,  607,  609,  610,  612,  615,
      627,  628,  552,  544,  548,  536,    0,  532,  522,  515,
      528,  506,  497,  507,  493,  190,  493,  125,  474,  483,
      630,  633,  648,  645,  639,  656,  663,  651,  671,  674,
      680,  683,  686,  695,  698,  701,  456,  499,  460,    0,
      465,  446,  449,  445,  447,  430,  406,  409,  434,    0,

      150,  422,  383,  343,  704,  716,  710,  713,  729,  721,
      728,  737,  740,  745,  748,  756,  753,  764,  769,  343,
      170,  323,  327,  325,    0,    0,  316,    0,    0,  307,
      118,  305,  202,  302,  293,  776,  771,  784,  787,  792,
      795,  800,  803,  808,  811,  819,  288,  284,  290,  272,
      257,  257,    0,  265,  243,  239, 1005,  256,  816,  832,
      827,  835,  840,  843,  858,    0,  228,  232,  237,    0,
        0,  215, 1005,  209,  207,    0,  851,  859,  864,  870,
      871,  876,  877, 1005,  213,  197,  191, 1005,    0,  892,
      879,  895,  178,  182,  157,  898,  901,  128,   93, 1005,

      904,  913,   94,   33,  921,  916,    0,   45,  910,  932,
        0,  929, 1005,  973,  975,   68
    } ;

static const flex_int16_t yy_def[417] =
    {   0,
      413,    1,  413,  413,  413,  413,  414,  413,  413,  415,
      415,  415,  415,  415,  415,  415,  415,  415,  415,  415,
      415,  415,  415,  415,  415,  413,   26,   26,   26,   26,
       26,   26,   26,   26,   26,   26,   26,   26,   26,   26,
       26,   26,  413,  414,  413,  413,  415,  415,  415,  415,
      415,  415,  415,  415,  415,  415,  415,  415,  415,  415,
      415,  415,  415,  415,  415,  415,  415,  415,  415,  415,
      415,  415,  415,  416,   26,   26,   26,   26,   26,   26,
       26,   26,   26,   26,   26,   26,   26,   26,   26,   26,
       26,   26,   26,   26,   26,   26,   26,   26,   26,   26,

       26,  413,  413,  415,  415,  415,  415,  415,  415,  415,
      415,  415,  415,  415,  415,  415,  415,  415,  415,  415,
      415,  415,  415,  415,  415,  415,  415,  415,  415,  415,
      415,  416,   26,   26,   26,   26,   26,   26,   26,   26,
       26,   26,   26,   26,   26,   26,   26,   26,   26,   26,
       26,   26,   26,   26,   26,   26,   26,   26,   26,   26,
      415,  415,  415,  415,  415,  415,  415,  415,  415,  415,
      415,  415,  415,  415,  415,  415,  415,  415,  413,  415,
      415,  415,  415,  415,   26,   26,   26,   26,   26,   26,
       26,   26,   26,   26,   26,   26,   26,   26,   26,   26,

       26,   26,   26,   26,   26,   26,   26,  415,  415,  415,
      415,  415,  415,  415,  415,  415,  415,  415,  415,  415,
      415,  415,  415,  415,  415,  413,  415,  415,  415,  415,
       26,   26,   26,   26,   26,   26,   26,   26,   26,   26,
       26,   26,   26,   26,   26,   26,   26,   26,   26,   26,
       26,   26,  415,  415,  415,  415,  415,  415,  415,  415,
      415,  415,  415,  415,  415,  413,  415,  415,  413,  415,
       26,   26,   26,   26,   26,   26,   26,   26,   26,   26,
       26,   26,   26,   26,   26,   26,  415,  415,  415,  415,
      415,  415,  415,  415,  415,  415,  415,  415,  413,  415,

      413,  415,  413,  415,   26,   26,   26,   26,   26,   26,
       26,   26,   26,   26,   26,   26,   26,   26,   26,  415,
      413,  415,  415,  415,  415,  415,  415,  415,  415,  415,
      413,  413,  413,  413,  415,   26,   26,   26,   26,   26,
       26,   26,   26,   26,   26,   26,  415,  413,  415,  415,
      415,  415,  415,  413,  413,  413,  413,  415,   26,   26,
       26,   26,   26,   26,   26,  415,  413,  415,  415,  415,
      415,  413,  413,  413,  415,  415,   26,   26,   26,   26,
       26,   26,   26,  413,  415,  415,  413,  413,  415,   26,
       26,   26,  415,  415,  413,   26,   26,  415,  415,  413,

       26,   26,  415,  415,   26,   26,  415,  415,   26,   26,
      415,   26,    0,  413,  413,  413
    } ;

static const flex_int16_t yy_nxt[1052] =
    {   0,
        4,    5,    6,    7,    8,    4,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
       23,   24,   25,    4,   26,   27,   28,   29,   30,   31,
       27,   27,   32,   33,   34,   27,   35,   36,   37,   27,
       38,   39,   40,   41,   42,   27,   46,   45,   48,   51,
       53,   60,   49,   56,   54,   57,   61,   62,   55,   64,
       58,   52,   50,   70,   46,   45,  119,  125,  129,   63,
      120,  132,  130,  411,  408,   71,  126,   65,   47,   47,
       47,   47,   47,   47,   47,   47,   47,   47,   47,   47,
       47,   47,   47,   47,   74,   75,   75,   76,   75,   75,

       75,   77,   75,   75,   75,   75,   75,   75,   75,   75,
       75,   78,   75,   75,   75,   75,   75,   75,   79,  331,
       75,   75,  407,   75,   75,   81,  301,   75,  404,   82,
       80,   75,   75,   83,   75,  164,   75,   75,   75,   84,
       87,   85,   75,   90,   75,   75,   86,  165,   88,   75,
      354,  301,   75,   89,   92,   91,   75,  110,   75,   75,
       75,   75,   75,   75,  302,   75,   75,   75,  111,  403,
       75,  321,   93,   95,   94,   75,   75,   75,   96,   75,
       98,   97,   75,   75,   75,   75,   75,  332,   75,   75,
      400,  266,   99,   75,  100,  101,   75,   75,   75,   75,

       75,   75,   75,  333,   75,   75,   75,  348,  135,   75,
      399,   75,   75,  398,   75,  395,   75,  133,  134,   75,
       75,   75,   75,   75,   75,   75,  299,   75,  136,   75,
      137,  394,  139,   75,   75,   75,   75,  138,   75,  356,
       75,  393,   75,  140,  142,  141,  389,   75,  388,   75,
       75,   75,   75,   75,   75,   75,   75,  387,   75,   75,
       75,   75,  144,   75,  143,  386,  385,  384,   75,   75,
      146,  145,   75,   75,   75,  374,   75,   75,   75,   75,
      375,  150,  373,   75,  376,   75,   75,  147,  148,   75,
       75,  151,  149,   75,   75,  372,  371,  370,  152,   75,

      154,   75,   75,  153,   75,   75,   75,  156,   75,  155,
       75,  157,   75,  369,   75,   75,   75,   75,  368,  158,
      367,   75,   75,  159,   75,   75,   75,  366,  358,   75,
       75,   75,  160,   75,   75,  357,  187,   75,   75,   75,
       75,  355,  185,  353,  352,  188,   75,   75,   75,  186,
       75,   75,  190,  351,   75,   75,   75,  189,   75,   75,
       75,  191,  350,   75,  349,   75,   75,  347,   75,  192,
       75,  193,   75,   75,   75,  195,   75,   75,   75,  335,
      194,   75,   75,   75,   75,  196,   75,   75,  197,  199,
       75,   75,   75,   75,   75,   75,   75,   75,  198,   75,

       75,  179,   75,   75,   75,  200,   75,  334,   75,   75,
       75,   75,   75,  202,   75,   75,  201,   75,   75,  203,
       75,   75,   75,  333,   75,   75,   75,  204,   75,   75,
       75,   75,   75,   75,   75,  331,   75,   75,   75,  205,
       75,   75,   75,   75,  330,  329,   75,  231,  207,   75,
      206,   75,   75,   75,   75,   75,   75,   75,   75,   75,
       75,   75,  234,   75,  233,  232,  328,  235,   75,   75,
       75,   75,   75,  327,  236,   75,   75,   75,   75,   75,
      239,   75,   75,  238,  326,  325,   75,  324,  237,   75,
       75,   75,   75,  323,   75,  322,  240,  241,   75,   75,

      321,  320,   75,   75,   75,   75,   75,   75,  242,   75,
       75,   75,   75,   75,  243,  304,  303,  300,  244,   75,
       75,   75,  245,   75,   75,  298,   75,   75,   75,  249,
       75,  297,  296,   75,  295,  248,  246,   75,   75,  247,
       75,   75,  250,   75,   75,   75,   75,   75,   75,   75,
       75,   75,  294,   75,  271,  251,  293,  292,   75,  291,
       75,   75,  252,   75,  272,   75,   75,   75,  273,   75,
       75,   75,  274,   75,   75,  290,  289,   75,   75,  275,
       75,   75,  276,  288,  287,  270,   75,   75,   75,   75,
       75,  277,   75,   75,  269,  278,   75,   75,   75,  268,

       75,   75,   75,   75,  280,  267,   75,  279,  266,   75,
       75,   75,   75,   75,   75,  281,   75,  266,   75,  265,
       75,  264,   75,   75,   75,  283,  263,  262,  261,  260,
       75,  282,   75,   75,  285,   75,   75,   75,  286,   75,
       75,   75,   75,  259,  258,   75,  257,   75,  284,   75,
       75,  256,   75,   75,   75,   75,   75,   75,   75,   75,
       75,  255,  305,   75,  254,   75,  253,   75,   75,   75,
       75,   75,  306,   75,   75,   75,  307,   75,   75,   75,
      230,   75,   75,  309,  308,   75,   75,  229,   75,   75,
      228,   75,  311,   75,  227,  312,   75,   75,  310,  301,

       75,   75,  313,   75,   75,  226,   75,  315,  225,   75,
       75,   75,   75,   75,   75,  314,   75,  321,  316,  317,
       75,   75,  224,   75,   75,   75,   75,   75,   75,  223,
       75,   75,  222,  319,   75,   75,   75,  318,   75,   75,
       75,   75,   75,   75,   75,  337,   75,   75,  221,  336,
       75,   75,  220,   75,   75,   75,   75,  338,   75,   75,
      219,   75,  339,   75,  340,  333,  342,   75,   75,   75,
       75,   75,  218,  217,   75,   75,  341,   75,   75,   75,
       75,  343,   75,   75,  216,   75,   75,  344,   75,  215,
       75,  345,  214,   75,   75,   75,   75,   75,  213,   75,

      359,   75,   75,  212,   75,  346,   75,  211,  210,   75,
       75,   75,  360,   75,   75,  362,   75,   75,   75,  361,
      209,   75,   75,  208,   75,   75,   75,   75,  363,   75,
       75,  184,   75,   75,   75,   75,  183,   75,   75,  182,
       75,   75,   75,   75,  181,   75,   75,  364,   75,   75,
      180,   75,  179,   75,  365,  377,   75,   75,   75,   75,
      378,   75,   75,  178,  177,   75,   75,   75,  379,   75,
       75,  176,   75,   75,  175,  380,  174,   75,  173,  381,
       75,   75,  382,   75,   75,   75,  383,  172,   75,   75,
       75,   75,  391,  390,   75,  171,   75,   75,   75,   75,

       75,   75,   75,   75,   75,   75,   75,   75,  170,   75,
       75,   75,  169,  397,  168,  392,   75,   75,   75,   75,
      396,   75,   75,  167,   75,   75,  166,   75,   75,  402,
       75,   75,   75,  401,   75,   75,   75,  163,   75,   75,
       75,   75,   75,   75,   75,  405,   75,   75,  406,  409,
       75,   75,  162,   75,  161,   75,   75,  410,   75,   75,
      412,   75,   75,  103,  131,  128,  127,  124,  123,   75,
      122,  121,   75,   44,  118,   44,   44,   47,   47,  117,
      116,  115,  114,  113,  112,  109,  108,  107,  106,  105,
      104,  103,  102,   43,   73,   72,   69,   68,   67,   66,

       59,   45,   43,  413,    3,  413,  413,  413,  413,  413,
      413,  413,  413,  413,  413,  413,  413,  413,  413,  413,
      413,  413,  413,  413,  413,  413,  413,  413,  413,  413,
      413,  413,  413,  413,  413,  413,  413,  413,  413,  413,
      413,  413,  413,  413,  413,  413,  413,  413,  413,  413,
      413
    } ;

static const flex_int16_t yy_chk[1052] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    9,    9,   10,   12,
       13,   16,   10,   14,   13,   14,   16,   17,   13,   18,
       14,   12,   10,   23,   45,   45,   64,   69,   72,   17,
       64,  416,   72,  408,  404,   23,   69,   18,   26,   26,
       26,   26,   26,   26,   26,   26,   26,   26,   26,   26,
       26,   26,   26,   26,   26,   26,   26,   26,   26,   26,

       26,   26,   26,   26,   26,   26,   26,   26,   26,   26,
       26,   26,   26,   26,   26,   26,   26,   27,   28,  331,
       28,   27,  403,   29,   28,   29,  268,   29,  399,   29,
       28,   27,   30,   29,   28,  107,   30,   29,   31,   30,
       31,   30,   31,   33,   32,   33,   30,  107,   32,   33,
      331,  301,   31,   32,   34,   33,   34,   54,   32,   33,
       34,   35,   37,   36,  268,   35,   37,   36,   54,  398,
       34,  321,   34,   36,   35,   35,   37,   36,   37,   38,
       39,   38,   39,   38,   42,   40,   39,  301,   42,   40,
      395,  266,   39,   38,   40,   41,   39,   41,   42,   40,

       75,   41,   76,  333,   75,   77,   76,  321,   78,   77,
      394,   41,   78,  393,   75,  387,   76,   76,   77,   77,
       79,   80,   78,   81,   79,   80,  266,   81,   79,   82,
       80,  386,   82,   82,   79,   80,   83,   81,   84,  333,
       83,  385,   84,   82,   84,   83,  375,   85,  374,   86,
       83,   85,   84,   86,   87,   88,   89,  372,   87,   88,
       89,   85,   87,   86,   86,  369,  368,  367,   87,   88,
       89,   88,   90,   91,   92,  356,   90,   91,   92,   93,
      358,   93,  355,   93,  358,   95,   90,   91,   92,   95,
       94,   94,   92,   93,   94,  354,  352,  351,   95,   95,

       97,   96,   97,   96,   94,   96,   97,   98,   98,   97,
       99,   99,   98,  350,   99,   96,   97,  100,  349,  100,
      348,  100,   98,  100,   99,  101,  133,  347,  335,  101,
      133,  100,  101,  134,  135,  334,  135,  134,  135,  101,
      133,  332,  133,  330,  327,  136,  136,  134,  135,  134,
      136,  137,  138,  324,  140,  137,  138,  136,  140,  139,
      136,  139,  323,  139,  322,  137,  138,  320,  140,  140,
      141,  141,  142,  139,  141,  143,  142,  143,  147,  304,
      142,  143,  147,  144,  141,  144,  142,  144,  145,  148,
      145,  143,  147,  148,  145,  149,  146,  144,  146,  149,

      146,  154,  150,  148,  145,  149,  150,  303,  152,  149,
      146,  151,  152,  151,  153,  151,  150,  155,  153,  155,
      156,  155,  152,  302,  156,  151,  154,  156,  153,  157,
      154,  155,  158,  157,  156,  299,  158,  159,  160,  157,
      154,  159,  160,  157,  298,  297,  158,  185,  160,  185,
      159,  159,  160,  185,  186,  187,  188,  189,  186,  187,
      188,  189,  188,  185,  187,  186,  296,  189,  186,  187,
      188,  189,  190,  295,  190,  191,  190,  192,  193,  191,
      193,  192,  193,  192,  294,  293,  190,  292,  191,  191,
      194,  192,  193,  291,  194,  289,  194,  195,  195,  196,

      288,  287,  195,  196,  194,  198,  199,  197,  196,  198,
      199,  197,  195,  196,  197,  270,  269,  267,  198,  198,
      199,  197,  199,  200,  201,  265,  202,  200,  201,  203,
      202,  264,  263,  203,  262,  202,  200,  200,  201,  201,
      202,  205,  204,  203,  204,  205,  206,  231,  204,  207,
      206,  231,  261,  207,  231,  205,  260,  259,  204,  258,
      206,  231,  207,  207,  232,  235,  232,  233,  233,  235,
      232,  233,  234,  236,  234,  256,  255,  236,  234,  235,
      232,  233,  236,  254,  253,  227,  238,  236,  234,  237,
      238,  237,  239,  237,  226,  238,  239,  241,  240,  225,

      238,  241,  240,  237,  241,  224,  239,  240,  246,  242,
      243,  241,  240,  242,  243,  242,  244,  223,  245,  222,
      244,  221,  245,  242,  243,  245,  219,  218,  217,  215,
      244,  244,  245,  246,  248,  247,  248,  246,  249,  247,
      248,  250,  249,  214,  213,  250,  212,  246,  247,  247,
      248,  211,  249,  251,  252,  250,  271,  251,  252,  272,
      271,  210,  271,  272,  209,  275,  208,  251,  252,  275,
      271,  274,  272,  272,  273,  274,  273,  278,  273,  275,
      184,  278,  276,  276,  274,  274,  276,  182,  273,  277,
      181,  278,  278,  277,  180,  279,  276,  279,  277,  285,

      280,  279,  280,  277,  280,  179,  281,  282,  178,  282,
      281,  279,  283,  282,  280,  281,  283,  306,  283,  284,
      281,  284,  177,  282,  285,  284,  283,  286,  285,  176,
      305,  286,  175,  286,  305,  284,  307,  285,  285,  308,
      307,  286,  306,  308,  305,  307,  306,  310,  174,  305,
      307,  310,  173,  308,  311,  309,  306,  309,  311,  309,
      172,  310,  310,  312,  311,  318,  313,  312,  311,  309,
      313,  314,  171,  170,  315,  314,  312,  312,  315,  317,
      313,  314,  316,  317,  169,  314,  316,  315,  315,  168,
      318,  316,  167,  317,  318,  319,  316,  337,  166,  319,

      336,  337,  336,  165,  318,  319,  336,  164,  163,  319,
      338,  337,  337,  339,  338,  339,  336,  339,  340,  338,
      162,  341,  340,  161,  338,  341,  342,  339,  342,  343,
      342,  131,  340,  343,  344,  341,  130,  345,  344,  128,
      342,  345,  359,  343,  127,  346,  359,  345,  344,  346,
      126,  345,  125,  361,  346,  359,  359,  361,  360,  346,
      360,  362,  360,  122,  121,  362,  363,  361,  361,  364,
      363,  120,  360,  364,  119,  362,  117,  377,  116,  363,
      363,  377,  365,  364,  365,  378,  365,  115,  365,  378,
      379,  377,  379,  378,  379,  114,  380,  381,  365,  378,

      380,  381,  382,  383,  379,  391,  382,  383,  113,  391,
      380,  381,  112,  391,  111,  382,  382,  383,  390,  391,
      390,  392,  390,  110,  396,  392,  109,  397,  396,  397,
      401,  397,  390,  396,  401,  392,  409,  106,  396,  402,
      409,  397,  406,  402,  401,  401,  406,  405,  402,  405,
      409,  405,  105,  402,  104,  412,  406,  406,  410,  412,
      410,  405,  410,  103,   73,   71,   70,   68,   67,  412,
       66,   65,  410,  414,   63,  414,  414,  415,  415,   61,
       60,   59,   58,   56,   55,   53,   52,   51,   50,   49,
       48,   46,   44,   43,   25,   24,   22,   21,   20,   19,

       15,    8,    5,    3,  413,  413,  413,  413,  413,  413,
      413,  413,  413,  413,  413,  413,  413,  413,  413,  413,
      413,  413,  413,  413,  413,  413,  413,  413,  413,  413,
      413,  413,  413,  413,  413,  413,  413,  413,  413,  413,
      413,  413,  413,  413,  413,  413,  413,  413,  413,  413,
      413
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexical.l"
/** Sección de definiciones **/
#line 3 "lexical.l"
#include "syntactic.tab.h"
void yyerror(char *);
#line 814 "lex.yy.c"
#line 815 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 11 "lexical.l"


#line 1035 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 414 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1005 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 13 "lexical.l"
{ return NEWLINE; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 14 "lexical.l"
{ return ASC; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 15 "lexical.l"
{ return ASC; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 16 "lexical.l"
{ return DESC; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 17 "lexical.l"
{ return DESC; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 18 "lexical.l"
{ return DIST; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 19 "lexical.l"
{ return DIST; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 20 "lexical.l"
{ return SELECT; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 21 "lexical.l"
{ return TO; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 22 "lexical.l"
{ return SELECT; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 23 "lexical.l"
{ return SELECT; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 24 "lexical.l"
{ return ALL; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 25 "lexical.l"
{ return FROM; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 26 "lexical.l"
{ return FROM; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 27 "lexical.l"
{ return THE; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 28 "lexical.l"
{ return THE; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 29 "lexical.l"
{ return THAT; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 30 "lexical.l"
{ return WITH; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 31 "lexical.l"
{ return INSERT; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 32 "lexical.l"
{ return INTO; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 33 "lexical.l"
{ return UPDATE; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 34 "lexical.l"
{ return DELETE; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 35 "lexical.l"
{ return WHERE; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 36 "lexical.l"
{ return SET; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 37 "lexical.l"
{ return SET; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 38 "lexical.l"
{ return VALUE; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 39 "lexical.l"
{ return EQUAL; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 40 "lexical.l"
{ return EQUAL; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 41 "lexical.l"
{ return DIFERENT; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 42 "lexical.l"
{ return AND; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 43 "lexical.l"
{ return OR; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 44 "lexical.l"
{ return TAB; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 45 "lexical.l"
{ return PLACE; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 46 "lexical.l"
{ return PLACE; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 47 "lexical.l"
{ return SHOW; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 48 "lexical.l"
{ return FOR; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 49 "lexical.l"
{ return MALE; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 50 "lexical.l"
{ return FEMALE; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 51 "lexical.l"
{ return MAYEQUAL; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 52 "lexical.l"
{ return JOIN; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 53 "lexical.l"
{ return JOIN; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 54 "lexical.l"
{ return GROUP_BY; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 55 "lexical.l"
{ return ORDER_BY; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 56 "lexical.l"
{ return ORDER_BY; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 57 "lexical.l"
{ return ORDER_BY; }
	YY_BREAK
case 46:
/* rule 46 can match eol */
YY_RULE_SETUP
#line 58 "lexical.l"
{ yylval.str = strdup(yytext); return STRING; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 59 "lexical.l"
{ yylval.flo = atof(yytext); return FLOAT; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 60 "lexical.l"
{ yylval.num = atoi(yytext); return NUMBER; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 61 "lexical.l"
{ yylval.str = strdup(yytext); return FIELD; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 62 "lexical.l"
{ yylval.str = strdup(yytext); return TABLE; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 63 "lexical.l"
{ /* Ignorar espacios en blanco */ }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 64 "lexical.l"
{ /* Caracteres no reconocidos */ }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 66 "lexical.l"
ECHO;
	YY_BREAK
#line 1359 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 414 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 414 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 413);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 66 "lexical.l"

int yywrap(){return 1;}

